namespace FS.GG.SDD.Commands.Tests

open System
open System.IO
open System.Text
open System.Text.Json.Nodes
open FS.GG.SDD.Artifacts
open FS.GG.SDD.Artifacts.SchemaVersion
open FS.GG.SDD.Commands.GenerationSourceSnapshot
open FS.GG.SDD.Commands.WorkModelSourceBundle
open FS.GG.SDD.Commands.WorkModelVerificationWave
open Xunit

module WorkModelVerificationWaveTests =
    let private workId = "sample"
    let private outputPath = "readiness/sample/work-model.json"

    let private requiredJson (value: JsonNode | null) : JsonNode =
        match value with
        | null -> failwith "fixture JSON node is absent"
        | node -> node

    let private fixture action =
        if OperatingSystem.IsLinux() then
            let root = Path.Combine(Path.GetTempPath(), "sdd-wave-" + Guid.NewGuid().ToString("N"))
            Directory.CreateDirectory(Path.Combine(root, ".fsgg")) |> ignore
            Directory.CreateDirectory(Path.Combine(root, "work/sample")) |> ignore
            try
                let paths =
                    [ ".fsgg/project.yml"; ".fsgg/sdd.yml"; ".fsgg/agents.yml"
                      "work/sample/spec.md" ]
                let selected: FileSnapshot list =
                    paths
                    |> List.map (fun path ->
                        let text =
                            if path = "work/sample/spec.md" then TestSupport.validSpec workId "Sample"
                            else "schemaVersion: 1\n"
                        let bytes = Encoding.UTF8.GetBytes text
                        File.WriteAllBytes(Path.Combine(root, path), bytes)
                        { Path = path; Text = text; RawBytes = Some bytes })
                let candidate: Candidate =
                    { Version = 2; WorkId = workId
                      Sources = selected |> List.map (fun source ->
                          { Path = source.Path; Digest = SchemaVersion.sha256Text source.Text }) }
                let generated =
                    Serialization.generateWorkModel
                        { WorkId = workId; Snapshots = selected
                          GeneratorVersion = (TestSupport.request FS.GG.SDD.Commands.CommandTypes.Analyze ".").GeneratorVersion
                          ExpectedOutputPath = Some outputPath }
                let captureRoot closedRoot declared =
                    match capture root closedRoot declared ExactBytes with
                    | Ok files -> files
                    | Error reason -> failwithf "fixture capture failed: %A" reason
                let captured =
                    captureRoot ".fsgg" paths.[0..2]
                    @ captureRoot "work/sample" [ paths.[3] ]
                action root selected candidate generated.Json captured
            finally Directory.Delete(root, true)

    let private prepared selected candidate json =
        match prepare workId outputPath json selected candidate with
        | Ok value -> value
        | Error reason -> failwithf "valid proposed output refused: %A" reason

    [<Fact>]
    let ``matching generated bytes and captured sources yield read-only preview`` () =
        fixture (fun _ selected candidate json captured ->
            match verifyCaptured (prepared selected candidate json) captured with
            | Error reason -> failwithf "valid preview refused: %A" reason
            | Ok preview ->
                Assert.Equal(outputPath, preview.OutputPath)
                Assert.Equal<string list>(candidate.Sources |> List.map _.Path |> List.sort,
                                          preview.SourcePaths |> List.sort))

    [<Fact>]
    let ``changed root source digest cannot borrow valid metadata and candidate`` () =
        fixture (fun _ selected candidate json captured ->
            let node = JsonNode.Parse json |> requiredJson
            let sources = (requiredJson node.["sources"]).AsArray()
            let first = requiredJson sources.[0]
            let sourceDigest = requiredJson first.["sourceDigest"]
            sourceDigest.["value"] <- JsonValue.Create(String.replicate 64 "0")
            // Red-before: the v2 source bundle has no proposed output bytes and still accepts
            // the unchanged selected/captured/candidate triple.
            match FS.GG.SDD.Commands.WorkModelSourceBundle.verify workId selected captured candidate with
            | Ok _ -> ()
            | Error reason -> failwithf "valid source-only control refused: %A" reason
            Assert.Equal(Error SourceMismatch,
                         prepare workId outputPath (node.ToJsonString()) selected candidate))

    [<Fact>]
    let ``stale candidate cannot authorize current generated bytes`` () =
        fixture (fun _ selected candidate json _ ->
            let staleSources =
                candidate.Sources
                |> List.mapi (fun index source ->
                    if index = 0 then { source with Digest = SchemaVersion.sha256Text "stale" }
                    else source)
            let stale = { candidate with Sources = staleSources }
            Assert.Equal(Error SourceMismatch, prepare workId outputPath json selected stale))

    [<Fact>]
    let ``wrong output identity and duplicate source row refuse before capture comparison`` () =
        fixture (fun _ selected candidate json _ ->
            Assert.Equal(Error WrongOutputPath,
                         prepare workId "readiness/other/work-model.json" json selected candidate)
            let node = JsonNode.Parse json |> requiredJson
            node.["workId"] <- JsonValue.Create "other"
            Assert.Equal(Error WrongOutputWorkId,
                         prepare workId outputPath (node.ToJsonString()) selected candidate)
            let duplicate = JsonNode.Parse json |> requiredJson
            let rows = (requiredJson duplicate.["sources"]).AsArray()
            let first = requiredJson rows.[0]
            let alias = first.DeepClone()
            let firstPath = (requiredJson first.["path"]).GetValue<string>()
            alias.["path"] <- JsonValue.Create(firstPath.ToUpperInvariant())
            rows.Add alias
            Assert.Equal(Error MalformedOutput,
                         prepare workId outputPath (duplicate.ToJsonString()) selected candidate))

    [<Fact>]
    let ``supplied changed physical capture refuses verified preview`` () =
        fixture (fun root selected candidate json captured ->
            File.WriteAllText(Path.Combine(root, "work/sample/spec.md"), "changed\n")
            let recaptured =
                match capture root "work/sample" [ "work/sample/spec.md" ] ExactBytes with
                | Ok files -> files
                | Error reason -> failwithf "changed source could not be recaptured: %A" reason
            let physical = captured |> List.filter (fun file -> file.Path <> "work/sample/spec.md")
            Assert.Equal(Error(Bundle(RawDrift "work/sample/spec.md")),
                         verifyCaptured (prepared selected candidate json) (physical @ recaptured)))
